### ISSUE TITLE
Publish project to maven central

### ISSUE THREAD

**Issue by sierra-delta** [tyczj/Tweedle#10] opened 2021-05-10 21:30 UTC
I can't get this project from jcenter.
Can you move it to maven central?

**Comment by tyczj** [comment] 2021-05-12 18:11
This has not been published to jcenter since 0.2, however where its being hosted I found that its not publicly available so I am in the process of moving it over now

**Comment by sierra-delta** [comment] 2021-05-13 18:37
Cool. Thank you for your work on this library.

**Comment by tyczj** [comment] 2021-05-15 00:39
Give it a try now it should be published to maven central. Let me know if you have any issues

**Comment by tyczj** [comment] 2021-05-18 01:59
Just an update here, having a heck of a time getting the library built and published correctly. When trying to add the dependency in another project I get build errors saying

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.github.tyczj:tweedle-android:0.3.0.
     Required by:
         project :app
      > No matching variant of io.github.tyczj:tweedle-android:0.3.0 was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'commonMainMetadataElements-published' capability io.github.tyczj:tweedle-android:0.3.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'metadataApiElements-published' capability io.github.tyczj:tweedle-android:0.3.0:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'releaseApiElements-published' capability io.github.tyczj:tweedle-android:0.3.0 declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'releaseRuntimeElements-published' capability io.github.tyczj:tweedle-android:0.3.0 declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
```

I dont know what the issue is at this point unfortunately

**Comment by tyczj** [comment] 2021-05-23 01:08
For now it seems you have to add the dependency like this

```
releaseImplementation 'io.github.tyczj:tweedle-android:0.3.2@aar'
debugImplementation 'io.github.tyczj:tweedle-android-debug:0.3.2@aar'
```

Trying to figure out how to have it like a normal Android dependency

**Comment by tyczj** [comment] 2021-06-01 23:56
Updated documentation for how to add android dependency

**Closed as completed by tyczj** 2021-06-01 23:56 UTC
